version: "2"

services:
  app_a:
    build: .
    expose:
      - "80"
  app_b:
    build: .
    expose:
      - "80"
  lb:
    image: dockercloud/haproxy
    links:
      - app_a
      - app_b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:80
